<?php 
$mysql_host = "localhost"; //Mysql host...
$mysql_user = ""; //Mysql user...
$mysql_password = ""; //Mysql password
$mysql_database = ""; //Mysql database...
$mysql_tableprefix = "syrup"; //Table prefix...

?>